### PR TITLE
fix: various small fixes

### PR DESCRIPTION
**Pull request by ciripel**
- fix `WalletConnectError` typo
- remove generated files from lib
- fix repository link in `pubspec.yaml`
- fix typo in `README.md`

### CODE REVIEW

**Comment by Luzzotica** [comment]
Is there a reason to not have the generated files in the repo? 

Does that not cause issues when publishing?

You might know more about that than I do. When you publish the repo, does it automatically generate the files? Or at what point would it do that?

**Comment by ciripel** [comment]
> Is there a reason to not have the generated files in the repo?
> 
> Does that not cause issues when publishing?
> 
> You might know more about that than I do. When you publish the repo, does it automatically generate the files? Or at what point would it do that?

Actually you are right. I've forgot that pub.dev needs them.

**Review by Luzzotica — APPROVED** [review]
Looks good

**Comment by Luzzotica** [comment]
Could you merge the changes from master into this branch please? I just added the code necessary to run tests in the github pipeline.

**Comment by ciripel** [comment]
> Could you merge the changes from master into this branch please? I just added the code necessary to run tests in the github pipeline.

now shall be good

**Comment by ciripel** [comment]
btw... if u need to automate publish to pub.dev u can use this as inspiration https://github.com/SimplioOfficial/sio_core_light/blob/master/.github/workflows/publish.yml
with https://github.com/SimplioOfficial/sio_core_light/blob/master/pub_login.sh

Or if u have a better way... i am waiting to see.

**Comment by Luzzotica** [comment]
I'm not sure why your tests are failing. 
I am going to make your changes personally really quick and merge them in. That will just be faster.
Thank you for bringing them to my attention.

As for the publishing stuff, thank you!! I'll figure it all out!

**Comment by ciripel** [comment]
> I'm not sure why your tests are failing. I am going to make your changes personally really quick and merge them in. That will just be faster. Thank you for bringing them to my attention.
> 
> As for the publishing stuff, thank you!! I'll figure it all out!

With pleasure

**Comment by ciripel** [comment]
Congratulations on the release!

**Pull request closed without merging**
